"""Command-line entrypoint for CI / pre-commit use.

Runs the test-generation pipeline on one or more Python files and writes a
Markdown report (for posting as a PR comment) plus, optionally, the generated
test files to a directory. Self-contained: no server or database required.

Usage:
    python -m app.cli path/to/a.py path/to/b.py \\
        --out report.md --tests-dir generated_tests
"""

import argparse
import os
import sys
from typing import Any, Dict, List

from app.agents.orchestrator import TestGenerationOrchestrator
from app.core.config import settings


def _analyze_file(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8", errors="ignore") as handle:
        code = handle.read()
    result = TestGenerationOrchestrator().analyze_from_text(code)
    result["_path"] = path
    return result


def _pass_rate(result: Dict[str, Any]) -> tuple[int, int]:
    results = result.get("test_results", [])
    passed = sum(1 for r in results if r.get("status") == "passed")
    return passed, len(results)


def build_report(results: List[Dict[str, Any]]) -> str:
    live = "LLM" if settings.has_groq_key else "offline demo"
    lines = [
        "## 🤖 Automated Test Generation",
        "",
        f"Analyzed **{len(results)}** changed Python file(s) — mode: `{live}`.",
        "",
        "| File | Functions | Tests | Pass rate | Coverage |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for res in results:
        stats = res.get("stats", {})
        cov = res.get("coverage", {})
        passed, total = _pass_rate(res)
        rate = f"{round(passed / total * 100)}%" if total else "—"
        coverage = (
            f"{cov.get('total_coverage', 0)}%" if cov.get("executed") else "not run"
        )
        lines.append(
            f"| `{os.path.basename(res['_path'])}` "
            f"| {stats.get('functions_analyzed', 0)} "
            f"| {stats.get('test_cases', 0)} "
            f"| {rate} | {coverage} |"
        )

    for res in results:
        tests = res.get("tests", [])
        if not tests:
            continue
        lines += ["", f"<details><summary>Generated tests for <code>{os.path.basename(res['_path'])}</code></summary>", ""]
        for test in tests:
            lines += [f"`{test['target_function']}`", "", "```python", test["content"], "```", ""]
        lines.append("</details>")

    lines += ["", "_Generated by TestCaseAI._"]
    return "\n".join(lines)


def _save_tests(results: List[Dict[str, Any]], tests_dir: str) -> None:
    os.makedirs(tests_dir, exist_ok=True)
    for res in results:
        for i, test in enumerate(res.get("tests", [])):
            name = f"test_{test['target_function']}_{i}.py"
            with open(os.path.join(tests_dir, name), "w", encoding="utf-8") as handle:
                handle.write(test["content"])


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate tests for Python files.")
    parser.add_argument("files", nargs="*", help="Python files to analyze")
    parser.add_argument("--out", help="Write the Markdown report to this path")
    parser.add_argument("--tests-dir", help="Save generated test files here")
    args = parser.parse_args(argv)

    files = [f for f in args.files if f.endswith(".py") and os.path.isfile(f)]
    if not files:
        print("No Python files to analyze.")
        return 0

    results = [_analyze_file(f) for f in files]
    report = build_report(results)
    print(report)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(report)
    if args.tests_dir:
        _save_tests(results, args.tests_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
